// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

using System.Diagnostics.CodeAnalysis;

[assembly: SuppressMessage("CodeQuality", "IDE0051:Quitar miembros privados no utilizados", Justification = "<pendiente>", Scope = "member", Target = "~F:DPSOsTelemetria2.Main.anio")]
[assembly: SuppressMessage("CodeQuality", "IDE0076:\"SuppressMessageAttribute\" global no válido", Justification = "<pendiente>")]
[assembly: SuppressMessage("Naming", "VSSpell001:Spell Check", Justification = "<pendiente>", Scope = "member", Target = "~F:DPSOsTelemetria2.Pozo._Telemetria")]
[assembly: SuppressMessage("Naming", "VSSpell001:Spell Check", Justification = "<pendiente>", Scope = "member", Target = "~M:DPSOsTelemetria2.Pozo.SendTelemetria")]
[assembly: SuppressMessage("Naming", "VSSpell001:Spell Check", Justification = "<pendiente>", Scope = "member", Target = "~P:DPSOsTelemetria2.Main.Anio")]
[assembly: SuppressMessage("Naming", "VSSpell001:Spell Check", Justification = "<pendiente>", Scope = "namespace", Target = "~N:DPSOsTelemetria2")]
[assembly: SuppressMessage("Naming", "VSSpell001:Spell Check", Justification = "<pendiente>", Scope = "namespace", Target = "~N:DPSOsTelemetria2.Administration")]
[assembly: SuppressMessage("Naming", "VSSpell001:Spell Check", Justification = "<pendiente>", Scope = "namespace", Target = "~N:DPSOsTelemetria2.Configuraciones")]
[assembly: SuppressMessage("Naming", "VSSpell001:Spell Check", Justification = "<pendiente>", Scope = "namespace", Target = "~N:DPSOsTelemetria2.Pozos.PozoBombeoCavidadProgresiva")]
[assembly: SuppressMessage("Naming", "VSSpell001:Spell Check", Justification = "<pendiente>", Scope = "namespace", Target = "~N:DPSOsTelemetria2.Pozos.PozoBombeoElectroCentrifugo")]
[assembly: SuppressMessage("Naming", "VSSpell001:Spell Check", Justification = "<pendiente>", Scope = "namespace", Target = "~N:DPSOsTelemetria2.Pozos.PozoBombeoFluyente")]
[assembly: SuppressMessage("Naming", "VSSpell001:Spell Check", Justification = "<pendiente>", Scope = "namespace", Target = "~N:DPSOsTelemetria2.Pozos.PozoBombeoFluyenteGas")]
[assembly: SuppressMessage("Naming", "VSSpell001:Spell Check", Justification = "<pendiente>", Scope = "namespace", Target = "~N:DPSOsTelemetria2.Pozos.PozoBombeoJetPump")]
[assembly: SuppressMessage("Naming", "VSSpell001:Spell Check", Justification = "<pendiente>", Scope = "namespace", Target = "~N:DPSOsTelemetria2.Pozos.PozoBombeoMecanico")]
[assembly: SuppressMessage("Naming", "VSSpell001:Spell Check", Justification = "<pendiente>", Scope = "namespace", Target = "~N:DPSOsTelemetria2.Pozos.PozoBombeoNeumatico")]
[assembly: SuppressMessage("Naming", "VSSpell001:Spell Check", Justification = "<pendiente>", Scope = "namespace", Target = "~N:DPSOsTelemetria2.Pozos.PozoBombeoNeumaticoIntermitente")]
[assembly: SuppressMessage("Naming", "VSSpell001:Spell Check", Justification = "<pendiente>", Scope = "type", Target = "~T:DPSOsTelemetria2.Administration.Administracion_Pozo")]
[assembly: SuppressMessage("Naming", "VSSpell001:Spell Check", Justification = "<pendiente>", Scope = "type", Target = "~T:DPSOsTelemetria2.Introducction")]
[assembly: SuppressMessage("Naming", "VSSpell001:Spell Check", Justification = "<pendiente>", Scope = "type", Target = "~T:DPSOsTelemetria2.Pozos.PozoBombeoFluyenteGas.TomaInformacion")]
[assembly: SuppressMessage("Naming", "VSSpell001:Spell Check", Justification = "<pendiente>", Scope = "type", Target = "~T:DPSOsTelemetria2.Pozos.PozoBombeoJetPump.TomaInformacion")]
[assembly: SuppressMessage("Naming", "VSSpell001:Spell Check", Justification = "<pendiente>", Scope = "type", Target = "~T:DPSOsTelemetria2.Pozos.PozoBombeoMecanico.TomaInformacion")]
[assembly: SuppressMessage("Naming", "VSSpell001:Spell Check", Justification = "<pendiente>", Scope = "type", Target = "~T:DPSOsTelemetria2.Pozos.PozoBombeoNeumatico.TomaInformacion")]
[assembly: SuppressMessage("Naming", "VSSpell001:Spell Check", Justification = "<pendiente>", Scope = "type", Target = "~T:DPSOsTelemetria2.Pozos.PozoBombeoNeumaticoIntermitente.TomaInformacion")]
[assembly: SuppressMessage("Style", "IDE0044:Agregar modificador de solo lectura", Justification = "<pendiente>", Scope = "member", Target = "~F:DPSOsTelemetria2.Config.newConfiguracion")]
[assembly: SuppressMessage("Style", "IDE0044:Agregar modificador de solo lectura", Justification = "<pendiente>", Scope = "member", Target = "~F:DPSOsTelemetria2.listaTiempo.dt")]
[assembly: SuppressMessage("Style", "IDE0044:Agregar modificador de solo lectura", Justification = "<pendiente>", Scope = "member", Target = "~F:DPSOsTelemetria2.Pozos.PozoBombeoMecanico.TomaInformacion.ListCCartaDinagrafica")]
[assembly: SuppressMessage("Style", "IDE1006:Estilos de nombres", Justification = "<pendiente>", Scope = "member", Target = "~M:DPSOsTelemetria2.Administration.Abrir_Eliminar.button1_Click(System.Object,System.EventArgs)")]
[assembly: SuppressMessage("Style", "IDE1006:Estilos de nombres", Justification = "<pendiente>", Scope = "member", Target = "~M:DPSOsTelemetria2.Administration.Abrir_Eliminar.button2_Click(System.Object,System.EventArgs)")]
[assembly: SuppressMessage("Style", "IDE1006:Estilos de nombres", Justification = "<pendiente>", Scope = "member", Target = "~M:DPSOsTelemetria2.Administration.Abrir_Eliminar.button3_Click(System.Object,System.EventArgs)")]
[assembly: SuppressMessage("Style", "IDE1006:Estilos de nombres", Justification = "<pendiente>", Scope = "member", Target = "~M:DPSOsTelemetria2.Administration.Abrir_Eliminar.textBox1_TextChanged(System.Object,System.EventArgs)")]
[assembly: SuppressMessage("Style", "IDE1006:Estilos de nombres", Justification = "<pendiente>", Scope = "member", Target = "~M:DPSOsTelemetria2.Administration.Administracion_Pozo.ddlTipoPozo_SelectedValueChanged(System.Object,System.EventArgs)")]
[assembly: SuppressMessage("Style", "IDE1006:Estilos de nombres", Justification = "<pendiente>", Scope = "member", Target = "~M:DPSOsTelemetria2.Configuraciones.Introducction.timer1_Tick(System.Object,System.EventArgs)")]
[assembly: SuppressMessage("Style", "IDE1006:Estilos de nombres", Justification = "<pendiente>", Scope = "member", Target = "~M:DPSOsTelemetria2.Configuraciones.Introducction.timer2_Tick(System.Object,System.EventArgs)")]
[assembly: SuppressMessage("Style", "IDE1006:Estilos de nombres", Justification = "<pendiente>", Scope = "member", Target = "~M:DPSOsTelemetria2.Configuraciones.Novedades.button1_Click(System.Object,System.EventArgs)")]
[assembly: SuppressMessage("Style", "IDE1006:Estilos de nombres", Justification = "<pendiente>", Scope = "member", Target = "~M:DPSOsTelemetria2.Configuraciones.Visualizacion.ddlIdioma_SelectedIndexChanged(System.Object,System.EventArgs)")]
[assembly: SuppressMessage("Style", "IDE1006:Estilos de nombres", Justification = "<pendiente>", Scope = "member", Target = "~M:DPSOsTelemetria2.Introducction.timer1_Tick(System.Object,System.EventArgs)")]
[assembly: SuppressMessage("Style", "IDE1006:Estilos de nombres", Justification = "<pendiente>", Scope = "member", Target = "~M:DPSOsTelemetria2.Introducction.timer2_Tick(System.Object,System.EventArgs)")]
[assembly: SuppressMessage("Style", "IDE1006:Estilos de nombres", Justification = "<pendiente>", Scope = "member", Target = "~M:DPSOsTelemetria2.listaTiempo.listaTiempo_Resize(System.Object,System.EventArgs)")]
[assembly: SuppressMessage("Style", "IDE1006:Estilos de nombres", Justification = "<pendiente>", Scope = "member", Target = "~M:DPSOsTelemetria2.Main.abrirToolStripMenuItem_Click(System.Object,System.EventArgs)")]
[assembly: SuppressMessage("Style", "IDE1006:Estilos de nombres", Justification = "<pendiente>", Scope = "member", Target = "~M:DPSOsTelemetria2.Main.guardarToolStripMenuItem_Click(System.Object,System.EventArgs)")]
[assembly: SuppressMessage("Style", "IDE1006:Estilos de nombres", Justification = "<pendiente>", Scope = "member", Target = "~M:DPSOsTelemetria2.Main.listaTiempo_Click(System.Object,System.EventArgs)")]
[assembly: SuppressMessage("Style", "IDE1006:Estilos de nombres", Justification = "<pendiente>", Scope = "member", Target = "~M:DPSOsTelemetria2.Main.nuevoToolStripMenuItem_Click(System.Object,System.EventArgs)")]
[assembly: SuppressMessage("Style", "IDE1006:Estilos de nombres", Justification = "<pendiente>", Scope = "member", Target = "~M:DPSOsTelemetria2.Main.timer1_Tick(System.Object,System.EventArgs)")]
[assembly: SuppressMessage("Style", "IDE1006:Estilos de nombres", Justification = "<pendiente>", Scope = "member", Target = "~M:DPSOsTelemetria2.Pozo.pictureBox1_Click(System.Object,System.EventArgs)")]
[assembly: SuppressMessage("Style", "IDE1006:Estilos de nombres", Justification = "<pendiente>", Scope = "member", Target = "~M:DPSOsTelemetria2.Pozos.PozoBombeoMecanico.TomaInformacion.releaseObject(System.Object)")]
[assembly: SuppressMessage("Style", "IDE1006:Estilos de nombres", Justification = "<pendiente>", Scope = "type", Target = "~T:DPSOsTelemetria2.listaTiempo")]
[assembly: SuppressMessage("Style", "IDE1006:Estilos de nombres", Justification = "<pendiente>", Scope = "type", Target = "~T:DPSOsTelemetria2.Pozos.PozoBombeoMecanico.TomaInformacion.lista")]
[assembly: SuppressMessage("Style", "IDE1006:Estilos de nombres", Justification = "<pendiente>", Scope = "type", Target = "~T:DPSOsTelemetria2.Pozos.PozoBombeoMecanico.TomaInformacion.oDinamometrica")]