// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

using System.Diagnostics.CodeAnalysis;

[assembly: SuppressMessage("CodeQuality", "IDE0051:Quitar miembros privados no utilizados", Justification = "<pendiente>", Scope = "member", Target = "~F:DPSOsTelemetria.Main.anio")]
[assembly: SuppressMessage("CodeQuality", "IDE0076:\"SuppressMessageAttribute\" global no válido", Justification = "<pendiente>")]
[assembly: SuppressMessage("Naming", "VSSpell001:Spell Check", Justification = "<pendiente>", Scope = "member", Target = "~F:DPSOsTelemetria.Pozo._Telemetria")]
[assembly: SuppressMessage("Naming", "VSSpell001:Spell Check", Justification = "<pendiente>", Scope = "member", Target = "~M:DPSOsTelemetria.Pozo.SendTelemetria")]
[assembly: SuppressMessage("Naming", "VSSpell001:Spell Check", Justification = "<pendiente>", Scope = "member", Target = "~P:DPSOsTelemetria.Main.Anio")]
[assembly: SuppressMessage("Naming", "VSSpell001:Spell Check", Justification = "<pendiente>", Scope = "namespace", Target = "~N:DPSOsTelemetria")]
[assembly: SuppressMessage("Naming", "VSSpell001:Spell Check", Justification = "<pendiente>", Scope = "namespace", Target = "~N:DPSOsTelemetria.Administration")]
[assembly: SuppressMessage("Naming", "VSSpell001:Spell Check", Justification = "<pendiente>", Scope = "namespace", Target = "~N:DPSOsTelemetria.Configuraciones")]
[assembly: SuppressMessage("Naming", "VSSpell001:Spell Check", Justification = "<pendiente>", Scope = "namespace", Target = "~N:DPSOsTelemetria.Pozos.PozoBombeoCavidadProgresiva")]
[assembly: SuppressMessage("Naming", "VSSpell001:Spell Check", Justification = "<pendiente>", Scope = "namespace", Target = "~N:DPSOsTelemetria.Pozos.PozoBombeoElectroCentrifugo")]
[assembly: SuppressMessage("Naming", "VSSpell001:Spell Check", Justification = "<pendiente>", Scope = "namespace", Target = "~N:DPSOsTelemetria.Pozos.PozoBombeoFluyente")]
[assembly: SuppressMessage("Naming", "VSSpell001:Spell Check", Justification = "<pendiente>", Scope = "namespace", Target = "~N:DPSOsTelemetria.Pozos.PozoBombeoFluyenteGas")]
[assembly: SuppressMessage("Naming", "VSSpell001:Spell Check", Justification = "<pendiente>", Scope = "namespace", Target = "~N:DPSOsTelemetria.Pozos.PozoBombeoJetPump")]
[assembly: SuppressMessage("Naming", "VSSpell001:Spell Check", Justification = "<pendiente>", Scope = "namespace", Target = "~N:DPSOsTelemetria.Pozos.PozoBombeoMecanico")]
[assembly: SuppressMessage("Naming", "VSSpell001:Spell Check", Justification = "<pendiente>", Scope = "namespace", Target = "~N:DPSOsTelemetria.Pozos.PozoBombeoNeumatico")]
[assembly: SuppressMessage("Naming", "VSSpell001:Spell Check", Justification = "<pendiente>", Scope = "namespace", Target = "~N:DPSOsTelemetria.Pozos.PozoBombeoNeumaticoIntermitente")]
[assembly: SuppressMessage("Naming", "VSSpell001:Spell Check", Justification = "<pendiente>", Scope = "type", Target = "~T:DPSOsTelemetria.Administration.Administracion_Pozo")]
[assembly: SuppressMessage("Naming", "VSSpell001:Spell Check", Justification = "<pendiente>", Scope = "type", Target = "~T:DPSOsTelemetria.Introducction")]
[assembly: SuppressMessage("Naming", "VSSpell001:Spell Check", Justification = "<pendiente>", Scope = "type", Target = "~T:DPSOsTelemetria.Pozos.PozoBombeoFluyenteGas.TomaInformacion")]
[assembly: SuppressMessage("Naming", "VSSpell001:Spell Check", Justification = "<pendiente>", Scope = "type", Target = "~T:DPSOsTelemetria.Pozos.PozoBombeoJetPump.TomaInformacion")]
[assembly: SuppressMessage("Naming", "VSSpell001:Spell Check", Justification = "<pendiente>", Scope = "type", Target = "~T:DPSOsTelemetria.Pozos.PozoBombeoMecanico.TomaInformacion")]
[assembly: SuppressMessage("Naming", "VSSpell001:Spell Check", Justification = "<pendiente>", Scope = "type", Target = "~T:DPSOsTelemetria.Pozos.PozoBombeoNeumatico.TomaInformacion")]
[assembly: SuppressMessage("Naming", "VSSpell001:Spell Check", Justification = "<pendiente>", Scope = "type", Target = "~T:DPSOsTelemetria.Pozos.PozoBombeoNeumaticoIntermitente.TomaInformacion")]
[assembly: SuppressMessage("Style", "IDE0044:Agregar modificador de solo lectura", Justification = "<pendiente>", Scope = "member", Target = "~F:DPSOsTelemetria.Config.newConfiguracion")]
[assembly: SuppressMessage("Style", "IDE0044:Agregar modificador de solo lectura", Justification = "<pendiente>", Scope = "member", Target = "~F:DPSOsTelemetria.listaTiempo.dt")]
[assembly: SuppressMessage("Style", "IDE0044:Agregar modificador de solo lectura", Justification = "<pendiente>", Scope = "member", Target = "~F:DPSOsTelemetria.Pozos.PozoBombeoMecanico.TomaInformacion.ListCCartaDinagrafica")]
[assembly: SuppressMessage("Style", "IDE1006:Estilos de nombres", Justification = "<pendiente>", Scope = "member", Target = "~M:DPSOsTelemetria.Administration.Abrir_Eliminar.button1_Click(System.Object,System.EventArgs)")]
[assembly: SuppressMessage("Style", "IDE1006:Estilos de nombres", Justification = "<pendiente>", Scope = "member", Target = "~M:DPSOsTelemetria.Administration.Abrir_Eliminar.button2_Click(System.Object,System.EventArgs)")]
[assembly: SuppressMessage("Style", "IDE1006:Estilos de nombres", Justification = "<pendiente>", Scope = "member", Target = "~M:DPSOsTelemetria.Administration.Abrir_Eliminar.button3_Click(System.Object,System.EventArgs)")]
[assembly: SuppressMessage("Style", "IDE1006:Estilos de nombres", Justification = "<pendiente>", Scope = "member", Target = "~M:DPSOsTelemetria.Administration.Abrir_Eliminar.textBox1_TextChanged(System.Object,System.EventArgs)")]
[assembly: SuppressMessage("Style", "IDE1006:Estilos de nombres", Justification = "<pendiente>", Scope = "member", Target = "~M:DPSOsTelemetria.Administration.Administracion_Pozo.ddlTipoPozo_SelectedValueChanged(System.Object,System.EventArgs)")]
[assembly: SuppressMessage("Style", "IDE1006:Estilos de nombres", Justification = "<pendiente>", Scope = "member", Target = "~M:DPSOsTelemetria.Configuraciones.Introducction.timer1_Tick(System.Object,System.EventArgs)")]
[assembly: SuppressMessage("Style", "IDE1006:Estilos de nombres", Justification = "<pendiente>", Scope = "member", Target = "~M:DPSOsTelemetria.Configuraciones.Introducction.timer2_Tick(System.Object,System.EventArgs)")]
[assembly: SuppressMessage("Style", "IDE1006:Estilos de nombres", Justification = "<pendiente>", Scope = "member", Target = "~M:DPSOsTelemetria.Configuraciones.Novedades.button1_Click(System.Object,System.EventArgs)")]
[assembly: SuppressMessage("Style", "IDE1006:Estilos de nombres", Justification = "<pendiente>", Scope = "member", Target = "~M:DPSOsTelemetria.Configuraciones.Visualizacion.ddlIdioma_SelectedIndexChanged(System.Object,System.EventArgs)")]
[assembly: SuppressMessage("Style", "IDE1006:Estilos de nombres", Justification = "<pendiente>", Scope = "member", Target = "~M:DPSOsTelemetria.Introducction.timer1_Tick(System.Object,System.EventArgs)")]
[assembly: SuppressMessage("Style", "IDE1006:Estilos de nombres", Justification = "<pendiente>", Scope = "member", Target = "~M:DPSOsTelemetria.Introducction.timer2_Tick(System.Object,System.EventArgs)")]
[assembly: SuppressMessage("Style", "IDE1006:Estilos de nombres", Justification = "<pendiente>", Scope = "member", Target = "~M:DPSOsTelemetria.listaTiempo.listaTiempo_Resize(System.Object,System.EventArgs)")]
[assembly: SuppressMessage("Style", "IDE1006:Estilos de nombres", Justification = "<pendiente>", Scope = "member", Target = "~M:DPSOsTelemetria.Main.abrirToolStripMenuItem_Click(System.Object,System.EventArgs)")]
[assembly: SuppressMessage("Style", "IDE1006:Estilos de nombres", Justification = "<pendiente>", Scope = "member", Target = "~M:DPSOsTelemetria.Main.guardarToolStripMenuItem_Click(System.Object,System.EventArgs)")]
[assembly: SuppressMessage("Style", "IDE1006:Estilos de nombres", Justification = "<pendiente>", Scope = "member", Target = "~M:DPSOsTelemetria.Main.listaTiempo_Click(System.Object,System.EventArgs)")]
[assembly: SuppressMessage("Style", "IDE1006:Estilos de nombres", Justification = "<pendiente>", Scope = "member", Target = "~M:DPSOsTelemetria.Main.nuevoToolStripMenuItem_Click(System.Object,System.EventArgs)")]
[assembly: SuppressMessage("Style", "IDE1006:Estilos de nombres", Justification = "<pendiente>", Scope = "member", Target = "~M:DPSOsTelemetria.Main.timer1_Tick(System.Object,System.EventArgs)")]
[assembly: SuppressMessage("Style", "IDE1006:Estilos de nombres", Justification = "<pendiente>", Scope = "member", Target = "~M:DPSOsTelemetria.Pozo.pictureBox1_Click(System.Object,System.EventArgs)")]
[assembly: SuppressMessage("Style", "IDE1006:Estilos de nombres", Justification = "<pendiente>", Scope = "member", Target = "~M:DPSOsTelemetria.Pozos.PozoBombeoMecanico.TomaInformacion.releaseObject(System.Object)")]
[assembly: SuppressMessage("Style", "IDE1006:Estilos de nombres", Justification = "<pendiente>", Scope = "type", Target = "~T:DPSOsTelemetria.listaTiempo")]
[assembly: SuppressMessage("Style", "IDE1006:Estilos de nombres", Justification = "<pendiente>", Scope = "type", Target = "~T:DPSOsTelemetria.Pozos.PozoBombeoMecanico.TomaInformacion.lista")]
[assembly: SuppressMessage("Style", "IDE1006:Estilos de nombres", Justification = "<pendiente>", Scope = "type", Target = "~T:DPSOsTelemetria.Pozos.PozoBombeoMecanico.TomaInformacion.oDinamometrica")]