//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Languages {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class DPSOsTelemetria {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DPSOsTelemetria() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Languages.DPSOsTelemetria", typeof(DPSOsTelemetria).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Information board.
        /// </summary>
        public static string Abrir_Eliminar {
            get {
                return ResourceManager.GetString("Abrir_Eliminar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a About....
        /// </summary>
        public static string AcercaDe {
            get {
                return ResourceManager.GetString("AcercaDe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a administrator.
        /// </summary>
        public static string Administrador {
            get {
                return ResourceManager.GetString("Administrador", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Archive.
        /// </summary>
        public static string Archivo {
            get {
                return ResourceManager.GetString("Archivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Arrange icons.
        /// </summary>
        public static string ArrangeIcons {
            get {
                return ResourceManager.GetString("ArrangeIcons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Attention.
        /// </summary>
        public static string Aviso {
            get {
                return ResourceManager.GetString("Aviso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Help.
        /// </summary>
        public static string Ayuda {
            get {
                return ResourceManager.GetString("Ayuda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The well {0} as it is open.
        /// </summary>
        public static string CantAbrir {
            get {
                return ResourceManager.GetString("CantAbrir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You can not remove the well {0} as it is open.
        /// </summary>
        public static string CantEliminar {
            get {
                return ResourceManager.GetString("CantEliminar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You can not modify the well {0} since it is open.
        /// </summary>
        public static string CantModify {
            get {
                return ResourceManager.GetString("CantModify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cascade.
        /// </summary>
        public static string Cascade {
            get {
                return ResourceManager.GetString("Cascade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Close all windows.
        /// </summary>
        public static string CloseAll {
            get {
                return ResourceManager.GetString("CloseAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Simulator: DPSOS Telemetry.
        /// </summary>
        public static string DPSOsTelemetry {
            get {
                return ResourceManager.GetString("DPSOsTelemetry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a English.
        /// </summary>
        public static string En {
            get {
                return ResourceManager.GetString("En", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Spanish.
        /// </summary>
        public static string Es {
            get {
                return ResourceManager.GetString("Es", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Spanish ( Mx ).
        /// </summary>
        public static string EsMx {
            get {
                return ResourceManager.GetString("EsMx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Do you want to register the information?.
        /// </summary>
        public static string Guardado {
            get {
                return ResourceManager.GetString("Guardado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Save.
        /// </summary>
        public static string GuardarArchivo {
            get {
                return ResourceManager.GetString("GuardarArchivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tool.
        /// </summary>
        public static string Herramienta {
            get {
                return ResourceManager.GetString("Herramienta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Language.
        /// </summary>
        public static string Idioma {
            get {
                return ResourceManager.GetString("Idioma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a List of timers.
        /// </summary>
        public static string listaTiempo {
            get {
                return ResourceManager.GetString("listaTiempo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Minimize all windows.
        /// </summary>
        public static string MinimizedAll {
            get {
                return ResourceManager.GetString("MinimizedAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a New.
        /// </summary>
        public static string Nuevo {
            get {
                return ResourceManager.GetString("Nuevo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Off.
        /// </summary>
        public static string Off {
            get {
                return ResourceManager.GetString("Off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a On.
        /// </summary>
        public static string On {
            get {
                return ResourceManager.GetString("On", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tile horizontal.
        /// </summary>
        public static string TileHorizontal {
            get {
                return ResourceManager.GetString("TileHorizontal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tile vertical.
        /// </summary>
        public static string TileVertical {
            get {
                return ResourceManager.GetString("TileVertical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Windows.
        /// </summary>
        public static string Ventanas {
            get {
                return ResourceManager.GetString("Ventanas", resourceCulture);
            }
        }
    }
}
