//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Languages {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Graphics {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Graphics() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Languages.Graphics", typeof(Graphics).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Influx.
        /// </summary>
        public static string AfluenciaPozo {
            get {
                return ResourceManager.GetString("AfluenciaPozo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Capacity.
        /// </summary>
        public static string Axis_Capacidad {
            get {
                return ResourceManager.GetString("Axis_Capacidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Load.
        /// </summary>
        public static string Axis_Carga {
            get {
                return ResourceManager.GetString("Axis_Carga", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Flow.
        /// </summary>
        public static string Axis_Caudal {
            get {
                return ResourceManager.GetString("Axis_Caudal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Displacement.
        /// </summary>
        public static string Axis_Desplazamiento {
            get {
                return ResourceManager.GetString("Axis_Desplazamiento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Percentage.
        /// </summary>
        public static string Axis_Porcentaje {
            get {
                return ResourceManager.GetString("Axis_Porcentaje", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pressure.
        /// </summary>
        public static string Axis_Presion {
            get {
                return ResourceManager.GetString("Axis_Presion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Depth.
        /// </summary>
        public static string Axis_Profundidad {
            get {
                return ResourceManager.GetString("Axis_Profundidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Temperature.
        /// </summary>
        public static string Axis_Temperatura {
            get {
                return ResourceManager.GetString("Axis_Temperatura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a BEP.
        /// </summary>
        public static string BEP {
            get {
                return ResourceManager.GetString("BEP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a BHP.
        /// </summary>
        public static string BHP {
            get {
                return ResourceManager.GetString("BHP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pump.
        /// </summary>
        public static string Bomba {
            get {
                return ResourceManager.GetString("Bomba", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Displacement.
        /// </summary>
        public static string DesplazamientoBomba {
            get {
                return ResourceManager.GetString("DesplazamientoBomba", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a East Deviation.
        /// </summary>
        public static string DesviacionEste {
            get {
                return ResourceManager.GetString("DesviacionEste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Horizontal Deviation.
        /// </summary>
        public static string DesviacionHorizontal {
            get {
                return ResourceManager.GetString("DesviacionHorizontal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Horizontal Deviation vs Vertical Depth.
        /// </summary>
        public static string DesviacionHorizontal_ProfundidadVertical {
            get {
                return ResourceManager.GetString("DesviacionHorizontal_ProfundidadVertical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a North Deviation.
        /// </summary>
        public static string DesviacionNorte {
            get {
                return ResourceManager.GetString("DesviacionNorte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Area.
        /// </summary>
        public static string DinamometricaArea {
            get {
                return ResourceManager.GetString("DinamometricaArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Subsurface Dynocard.
        /// </summary>
        public static string DinamometricaFondo {
            get {
                return ResourceManager.GetString("DinamometricaFondo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Surface Dynocard.
        /// </summary>
        public static string DinamometricaSuperficie {
            get {
                return ResourceManager.GetString("DinamometricaSuperficie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Efficiency.
        /// </summary>
        public static string Eficiencia {
            get {
                return ResourceManager.GetString("Eficiencia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fails.
        /// </summary>
        public static string Falla {
            get {
                return ResourceManager.GetString("Falla", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fo Max.
        /// </summary>
        public static string FoMax {
            get {
                return ResourceManager.GetString("FoMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Education.
        /// </summary>
        public static string Formacion {
            get {
                return ResourceManager.GetString("Formacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a General.
        /// </summary>
        public static string General {
            get {
                return ResourceManager.GetString("General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Goodman.
        /// </summary>
        public static string Goodman {
            get {
                return ResourceManager.GetString("Goodman", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Gas gradient.
        /// </summary>
        public static string GradienteGas {
            get {
                return ResourceManager.GetString("GradienteGas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Dynamic gradient.
        /// </summary>
        public static string GradientePresion {
            get {
                return ResourceManager.GetString("GradientePresion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Temperature Gradient.
        /// </summary>
        public static string GradienteTemperatura {
            get {
                return ResourceManager.GetString("GradienteTemperatura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 45 Hz.
        /// </summary>
        public static string H45 {
            get {
                return ResourceManager.GetString("H45", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 50 Hz.
        /// </summary>
        public static string H50 {
            get {
                return ResourceManager.GetString("H50", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 55 Hz.
        /// </summary>
        public static string H55 {
            get {
                return ResourceManager.GetString("H55", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 60 Hz.
        /// </summary>
        public static string H60 {
            get {
                return ResourceManager.GetString("H60", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 65 Hz.
        /// </summary>
        public static string H65 {
            get {
                return ResourceManager.GetString("H65", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 70 Hz.
        /// </summary>
        public static string H70 {
            get {
                return ResourceManager.GetString("H70", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 75 Hz.
        /// </summary>
        public static string H75 {
            get {
                return ResourceManager.GetString("H75", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 80 Hz.
        /// </summary>
        public static string H80 {
            get {
                return ResourceManager.GetString("H80", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Injection.
        /// </summary>
        public static string Inyeccion {
            get {
                return ResourceManager.GetString("Inyeccion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a IPR..
        /// </summary>
        public static string Ipr {
            get {
                return ResourceManager.GetString("Ipr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Prod..
        /// </summary>
        public static string Ite {
            get {
                return ResourceManager.GetString("Ite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Maximum.
        /// </summary>
        public static string Max {
            get {
                return ResourceManager.GetString("Max", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Max Effort.
        /// </summary>
        public static string MaxEfford {
            get {
                return ResourceManager.GetString("MaxEfford", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Minimum.
        /// </summary>
        public static string Min {
            get {
                return ResourceManager.GetString("Min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Min Tension.
        /// </summary>
        public static string MinTension {
            get {
                return ResourceManager.GetString("MinTension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Model.
        /// </summary>
        public static string Model {
            get {
                return ResourceManager.GetString("Model", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Dynamic Level.
        /// </summary>
        public static string NivelDinamico {
            get {
                return ResourceManager.GetString("NivelDinamico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Optimal.
        /// </summary>
        public static string Optimo {
            get {
                return ResourceManager.GetString("Optimo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a VOP Depth.
        /// </summary>
        public static string PerfilPresion1 {
            get {
                return ResourceManager.GetString("PerfilPresion1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pressure Gradient in TP.
        /// </summary>
        public static string PerfilPresion2 {
            get {
                return ResourceManager.GetString("PerfilPresion2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pressure Gradient in TR.
        /// </summary>
        public static string PerfilPresion3 {
            get {
                return ResourceManager.GetString("PerfilPresion3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PIP.
        /// </summary>
        public static string PIP {
            get {
                return ResourceManager.GetString("PIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pipe.
        /// </summary>
        public static string Pipe {
            get {
                return ResourceManager.GetString("Pipe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PKC.
        /// </summary>
        public static string PKC {
            get {
                return ResourceManager.GetString("PKC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PKO.
        /// </summary>
        public static string PKO {
            get {
                return ResourceManager.GetString("PKO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Flowing BHP.
        /// </summary>
        public static string Presion {
            get {
                return ResourceManager.GetString("Presion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Measured Depth.
        /// </summary>
        public static string ProfundidadMedida {
            get {
                return ResourceManager.GetString("ProfundidadMedida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Drilling depth.
        /// </summary>
        public static string ProfundidadPerforacion {
            get {
                return ResourceManager.GetString("ProfundidadPerforacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Vertical Depth.
        /// </summary>
        public static string ProfundidadVertical {
            get {
                return ResourceManager.GetString("ProfundidadVertical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Point of Operation.
        /// </summary>
        public static string PtoOperacion {
            get {
                return ResourceManager.GetString("PtoOperacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Optimal point of operation.
        /// </summary>
        public static string PtoOptimo {
            get {
                return ResourceManager.GetString("PtoOptimo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Qgi.
        /// </summary>
        public static string Qgi {
            get {
                return ResourceManager.GetString("Qgi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sensitivity.
        /// </summary>
        public static string Sensitivity {
            get {
                return ResourceManager.GetString("Sensitivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Severity Dogleg.
        /// </summary>
        public static string SeveridadDogleg {
            get {
                return ResourceManager.GetString("SeveridadDogleg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Oversized.
        /// </summary>
        public static string Sobredimencionado {
            get {
                return ResourceManager.GetString("Sobredimencionado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Undersized.
        /// </summary>
        public static string Subdimencionado {
            get {
                return ResourceManager.GetString("Subdimencionado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Subsurface.
        /// </summary>
        public static string Subsuperficial {
            get {
                return ResourceManager.GetString("Subsuperficial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Submergence.
        /// </summary>
        public static string Sumergencia {
            get {
                return ResourceManager.GetString("Sumergencia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Superficial.
        /// </summary>
        public static string Superficial {
            get {
                return ResourceManager.GetString("Superficial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Survey.
        /// </summary>
        public static string Survey {
            get {
                return ResourceManager.GetString("Survey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Current.
        /// </summary>
        public static string TakeInformation {
            get {
                return ResourceManager.GetString("TakeInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Under Cap.
        /// </summary>
        public static string TamanioTapon1 {
            get {
                return ResourceManager.GetString("TamanioTapon1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cap.
        /// </summary>
        public static string TamanioTapon2 {
            get {
                return ResourceManager.GetString("TamanioTapon2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a About Cap.
        /// </summary>
        public static string TamanioTapon3 {
            get {
                return ResourceManager.GetString("TamanioTapon3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tapered.
        /// </summary>
        public static string Taped {
            get {
                return ResourceManager.GetString("Taped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Target.
        /// </summary>
        public static string Target {
            get {
                return ResourceManager.GetString("Target", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a TDH.
        /// </summary>
        public static string TDH {
            get {
                return ResourceManager.GetString("TDH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Failures.
        /// </summary>
        public static string TipoParo {
            get {
                return ResourceManager.GetString("TipoParo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Top Tapered.
        /// </summary>
        public static string TopTaped {
            get {
                return ResourceManager.GetString("TopTaped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Valve.
        /// </summary>
        public static string Valvula {
            get {
                return ResourceManager.GetString("Valvula", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Open Valve - Does not inject.
        /// </summary>
        public static string ValvulaAbierta {
            get {
                return ResourceManager.GetString("ValvulaAbierta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Valve Closed.
        /// </summary>
        public static string ValvulaCerrada {
            get {
                return ResourceManager.GetString("ValvulaCerrada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Open Valve - Inject.
        /// </summary>
        public static string ValvulaInyecta {
            get {
                return ResourceManager.GetString("ValvulaInyecta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a East view.
        /// </summary>
        public static string VistaEste {
            get {
                return ResourceManager.GetString("VistaEste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a North view.
        /// </summary>
        public static string VistaNorte {
            get {
                return ResourceManager.GetString("VistaNorte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Plant view.
        /// </summary>
        public static string VistaPlanta {
            get {
                return ResourceManager.GetString("VistaPlanta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Vlp..
        /// </summary>
        public static string Vlp {
            get {
                return ResourceManager.GetString("Vlp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Wrf.
        /// </summary>
        public static string Wrf {
            get {
                return ResourceManager.GetString("Wrf", resourceCulture);
            }
        }
    }
}
