//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Languages {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Pozo {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Pozo() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Languages.Pozo", typeof(Pozo).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Add.
        /// </summary>
        public static string Agregar {
            get {
                return ResourceManager.GetString("Agregar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You must make some changes to update.
        /// </summary>
        public static string Aviso {
            get {
                return ResourceManager.GetString("Aviso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Dynocard.
        /// </summary>
        public static string CartaDinagrafica {
            get {
                return ResourceManager.GetString("CartaDinagrafica", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Operational data.
        /// </summary>
        public static string DatosOperativos {
            get {
                return ResourceManager.GetString("DatosOperativos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Filling efficiency.
        /// </summary>
        public static string DoEficienciaLlenado {
            get {
                return ResourceManager.GetString("DoEficienciaLlenado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pump operating frequency.
        /// </summary>
        public static string DoFrecuenciaOperacionBomba {
            get {
                return ResourceManager.GetString("DoFrecuenciaOperacionBomba", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Injection gas expenditure.
        /// </summary>
        public static string DoGastoGasInyeccion {
            get {
                return ResourceManager.GetString("DoGastoGasInyeccion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Specific gravity of injection gas.
        /// </summary>
        public static string DoGravedadEspecificaGasInyeccion {
            get {
                return ResourceManager.GetString("DoGravedadEspecificaGasInyeccion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Stroke length.
        /// </summary>
        public static string DoLongitudCarrera {
            get {
                return ResourceManager.GetString("DoLongitudCarrera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a TP well fluid level.
        /// </summary>
        public static string DoNivelFluidoPozoTp {
            get {
                return ResourceManager.GetString("DoNivelFluidoPozoTp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a TR well fluid level.
        /// </summary>
        public static string DoNivelFluidoPozoTr {
            get {
                return ResourceManager.GetString("DoNivelFluidoPozoTr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Available pressure.
        /// </summary>
        public static string DoPresionDisponible {
            get {
                return ResourceManager.GetString("DoPresionDisponible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pump inlet pressure.
        /// </summary>
        public static string DoPresionEntradaBomba {
            get {
                return ResourceManager.GetString("DoPresionEntradaBomba", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pressure in discharge line.
        /// </summary>
        public static string DoPresionLineaDescarga {
            get {
                return ResourceManager.GetString("DoPresionLineaDescarga", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tubing head pressure.
        /// </summary>
        public static string DoPresionTuberiaProduccion {
            get {
                return ResourceManager.GetString("DoPresionTuberiaProduccion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Casing head pressure.
        /// </summary>
        public static string DoPresionTuberiaRevestimiento {
            get {
                return ResourceManager.GetString("DoPresionTuberiaRevestimiento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Effective submergence of the pump.
        /// </summary>
        public static string DoSumergenciaEfectivaBomba {
            get {
                return ResourceManager.GetString("DoSumergenciaEfectivaBomba", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Surface temperature.
        /// </summary>
        public static string DoTemperaturaSuperficie {
            get {
                return ResourceManager.GetString("DoTemperaturaSuperficie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Engine speed.
        /// </summary>
        public static string DoVelocidadMotor {
            get {
                return ResourceManager.GetString("DoVelocidadMotor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pumping unit speed.
        /// </summary>
        public static string DoVelocidadUnidadBombeo {
            get {
                return ResourceManager.GetString("DoVelocidadUnidadBombeo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Delete.
        /// </summary>
        public static string Eliminar {
            get {
                return ResourceManager.GetString("Eliminar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sends number.
        /// </summary>
        public static string Envio {
            get {
                return ResourceManager.GetString("Envio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Correct transmission.
        /// </summary>
        public static string EnvioCorrecto {
            get {
                return ResourceManager.GetString("EnvioCorrecto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Incorrect transmission.
        /// </summary>
        public static string EnvioIncorrecto {
            get {
                return ResourceManager.GetString("EnvioIncorrecto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No charge any dynacard..
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a File error.\nNo charge any dynacard..
        /// </summary>
        public static string ErrorCarta {
            get {
                return ResourceManager.GetString("ErrorCarta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a {0}: The minimum value {1} must be greater than or equal to 0.
        /// </summary>
        public static string GreaterThan {
            get {
                return ResourceManager.GetString("GreaterThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a {0}: The minimum value {1} must be less than the maximum value {2}.
        /// </summary>
        public static string GreaterThanValue {
            get {
                return ResourceManager.GetString("GreaterThanValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Next update.
        /// </summary>
        public static string ProxActualizacion {
            get {
                return ResourceManager.GetString("ProxActualizacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Timer.
        /// </summary>
        public static string Temporizador {
            get {
                return ResourceManager.GetString("Temporizador", resourceCulture);
            }
        }
    }
}
