//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Languages {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Pozo {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Pozo() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Languages.Pozo", typeof(Pozo).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Add.
        /// </summary>
        public static string Agregar {
            get {
                return ResourceManager.GetString("Agregar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You must make some changes to update.
        /// </summary>
        public static string Aviso {
            get {
                return ResourceManager.GetString("Aviso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Load on polished bar.
        /// </summary>
        public static string CargaSobreBarraPulida {
            get {
                return ResourceManager.GetString("CargaSobreBarraPulida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Dynocard.
        /// </summary>
        public static string CartaDinagrafica {
            get {
                return ResourceManager.GetString("CartaDinagrafica", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Manual data.
        /// </summary>
        public static string DatosManual {
            get {
                return ResourceManager.GetString("DatosManual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Filling efficiency.
        /// </summary>
        public static string EficienciaLlenado {
            get {
                return ResourceManager.GetString("EficienciaLlenado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Delete.
        /// </summary>
        public static string Eliminar {
            get {
                return ResourceManager.GetString("Eliminar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Emulsion.
        /// </summary>
        public static string Emulsion {
            get {
                return ResourceManager.GetString("Emulsion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sends number.
        /// </summary>
        public static string Envio {
            get {
                return ResourceManager.GetString("Envio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Correct transmission.
        /// </summary>
        public static string EnvioCorrecto {
            get {
                return ResourceManager.GetString("EnvioCorrecto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Incorrect transmission.
        /// </summary>
        public static string EnvioIncorrecto {
            get {
                return ResourceManager.GetString("EnvioIncorrecto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No charge any dynacard..
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a File error.\nNo charge any dynacard..
        /// </summary>
        public static string ErrorCarta {
            get {
                return ResourceManager.GetString("ErrorCarta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pump operating frequency.
        /// </summary>
        public static string FrecuenciaOperacionBomba {
            get {
                return ResourceManager.GetString("FrecuenciaOperacionBomba", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Net Oil Production.
        /// </summary>
        public static string GastoAceite {
            get {
                return ResourceManager.GetString("GastoAceite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Water production.
        /// </summary>
        public static string GastoAgua {
            get {
                return ResourceManager.GetString("GastoAgua", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Gas production.
        /// </summary>
        public static string GastoGas {
            get {
                return ResourceManager.GetString("GastoGas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Injection gas expenditure.
        /// </summary>
        public static string GastoGasInyeccion {
            get {
                return ResourceManager.GetString("GastoGasInyeccion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Gross Production.
        /// </summary>
        public static string GastoLiquido {
            get {
                return ResourceManager.GetString("GastoLiquido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Well Testing Gross Production.
        /// </summary>
        public static string GastoLiquidoPruebaProduccion {
            get {
                return ResourceManager.GetString("GastoLiquidoPruebaProduccion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Specific gravity of injection gas.
        /// </summary>
        public static string GravedadEspecificaGasInyeccion {
            get {
                return ResourceManager.GetString("GravedadEspecificaGasInyeccion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Gas produced specific gravity.
        /// </summary>
        public static string GravedadEspecificaGasProducido {
            get {
                return ResourceManager.GetString("GravedadEspecificaGasProducido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Oil density.
        /// </summary>
        public static string GravedadPetroleo {
            get {
                return ResourceManager.GetString("GravedadPetroleo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a {0}: The minimum value {1} must be greater than or equal to 0.
        /// </summary>
        public static string GreaterThan {
            get {
                return ResourceManager.GetString("GreaterThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a {0}: The minimum value {1} must be less than the maximum value {2}.
        /// </summary>
        public static string GreaterThanValue {
            get {
                return ResourceManager.GetString("GreaterThanValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Stroke length.
        /// </summary>
        public static string LongitudCarrera {
            get {
                return ResourceManager.GetString("LongitudCarrera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a TP well fluid level.
        /// </summary>
        public static string NivelFluidoPozoTp {
            get {
                return ResourceManager.GetString("NivelFluidoPozoTp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a TR well fluid level.
        /// </summary>
        public static string NivelFluidoPozoTr {
            get {
                return ResourceManager.GetString("NivelFluidoPozoTr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Operating data.
        /// </summary>
        public static string OperativeData {
            get {
                return ResourceManager.GetString("OperativeData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a % BSW.
        /// </summary>
        public static string PorcentajeAguaSedimento {
            get {
                return ResourceManager.GetString("PorcentajeAguaSedimento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Available pressure.
        /// </summary>
        public static string PresionDisponible {
            get {
                return ResourceManager.GetString("PresionDisponible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pump inlet pressure.
        /// </summary>
        public static string PresionEntradaBomba {
            get {
                return ResourceManager.GetString("PresionEntradaBomba", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pressure in discharge line.
        /// </summary>
        public static string PresionLineaDescarga {
            get {
                return ResourceManager.GetString("PresionLineaDescarga", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tubing head pressure.
        /// </summary>
        public static string PresionTuberiaProduccion {
            get {
                return ResourceManager.GetString("PresionTuberiaProduccion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Casing head pressure.
        /// </summary>
        public static string PresionTuberiaRevestimiento {
            get {
                return ResourceManager.GetString("PresionTuberiaRevestimiento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Production data.
        /// </summary>
        public static string ProductionData {
            get {
                return ResourceManager.GetString("ProductionData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Next update.
        /// </summary>
        public static string ProxActualizacion {
            get {
                return ResourceManager.GetString("ProxActualizacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a GOR.
        /// </summary>
        public static string RelacionGasAceite {
            get {
                return ResourceManager.GetString("RelacionGasAceite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Water salinity.
        /// </summary>
        public static string SalinidadAgua {
            get {
                return ResourceManager.GetString("SalinidadAgua", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Effective submergence of the pump.
        /// </summary>
        public static string SumergenciaEfectivaBomba {
            get {
                return ResourceManager.GetString("SumergenciaEfectivaBomba", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Surface temperature.
        /// </summary>
        public static string TemperaturaSuperficie {
            get {
                return ResourceManager.GetString("TemperaturaSuperficie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Timer.
        /// </summary>
        public static string Temporizador {
            get {
                return ResourceManager.GetString("Temporizador", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Engine speed.
        /// </summary>
        public static string VelocidadMotor {
            get {
                return ResourceManager.GetString("VelocidadMotor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pumping unit speed.
        /// </summary>
        public static string VelocidadUnidadBombeo {
            get {
                return ResourceManager.GetString("VelocidadUnidadBombeo", resourceCulture);
            }
        }
    }
}
