//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Languages {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Setups {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Setups() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Languages.Setups", typeof(Setups).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Check for Updates.
        /// </summary>
        public static string Actualizaciones {
            get {
                return ResourceManager.GetString("Actualizaciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Software update.
        /// </summary>
        public static string ActualizacionPrograma {
            get {
                return ResourceManager.GetString("ActualizacionPrograma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a © {0} EnTecPro I-Services..
        /// </summary>
        public static string Copyright {
            get {
                return ResourceManager.GetString("Copyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Number of decimal places.
        /// </summary>
        public static string Decimales {
            get {
                return ResourceManager.GetString("Decimales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Example:.
        /// </summary>
        public static string Ejemplo {
            get {
                return ResourceManager.GetString("Ejemplo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a English.
        /// </summary>
        public static string En {
            get {
                return ResourceManager.GetString("En", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Spanish.
        /// </summary>
        public static string Es {
            get {
                return ResourceManager.GetString("Es", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Spanish ( Mx ).
        /// </summary>
        public static string EsMx {
            get {
                return ResourceManager.GetString("EsMx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Guides.
        /// </summary>
        public static string Guia {
            get {
                return ResourceManager.GetString("Guia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Language.
        /// </summary>
        public static string Idioma {
            get {
                return ResourceManager.GetString("Idioma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a License Agreement.
        /// </summary>
        public static string LicenseAgreement {
            get {
                return ResourceManager.GetString("LicenseAgreement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Licenses.
        /// </summary>
        public static string Licenses {
            get {
                return ResourceManager.GetString("Licenses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a List of transmissions.
        /// </summary>
        public static string ListaPozos {
            get {
                return ResourceManager.GetString("ListaPozos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a To access this modality, you must have at least 1 well in transmission.
        ///- From the menu, select {0}→{1}.....
        /// </summary>
        public static string ListaPozos1 {
            get {
                return ResourceManager.GetString("ListaPozos1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a This window contains main information of the times and status of the transmission made.
        /// </summary>
        public static string ListaPozos2 {
            get {
                return ResourceManager.GetString("ListaPozos2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a {0} is up to date.
        /// </summary>
        public static string MainLabel {
            get {
                return ResourceManager.GetString("MainLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Create new well.
        /// </summary>
        public static string newPozo {
            get {
                return ResourceManager.GetString("newPozo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a - Use the keyboard shortcut Ctrl+N (Mac: Cmd+N);
        ///- From the menu, select {0}→{1}.....
        /// </summary>
        public static string newPozo1 {
            get {
                return ResourceManager.GetString("newPozo1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Name.
        /// </summary>
        public static string newPozo2 {
            get {
                return ResourceManager.GetString("newPozo2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Token *must be unique for each well.
        /// </summary>
        public static string newPozo3 {
            get {
                return ResourceManager.GetString("newPozo3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Type of well.
        /// </summary>
        public static string newPozo4 {
            get {
                return ResourceManager.GetString("newPozo4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a System of units to be used.
        /// </summary>
        public static string newPozo5 {
            get {
                return ResourceManager.GetString("newPozo5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a What&apos;s new:.
        /// </summary>
        public static string News {
            get {
                return ResourceManager.GetString("News", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Privacy.
        /// </summary>
        public static string Privacy {
            get {
                return ResourceManager.GetString("Privacy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Release Notes.
        /// </summary>
        public static string ReleaseNotes {
            get {
                return ResourceManager.GetString("ReleaseNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Terms.
        /// </summary>
        public static string Terms {
            get {
                return ResourceManager.GetString("Terms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Data transmission.
        /// </summary>
        public static string TransmisionDatos {
            get {
                return ResourceManager.GetString("TransmisionDatos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a - Use the keyboard shortcut Ctrl+O (Mac: Cmd+O);
        ///- From the menu, select {0}→{1}.....
        /// </summary>
        public static string TransmisionDatos1 {
            get {
                return ResourceManager.GetString("TransmisionDatos1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Minimum value.
        /// </summary>
        public static string TransmisionDatos10 {
            get {
                return ResourceManager.GetString("TransmisionDatos10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Maximum value.
        /// </summary>
        public static string TransmisionDatos11 {
            get {
                return ResourceManager.GetString("TransmisionDatos11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Frequency time.
        /// </summary>
        public static string TransmisionDatos12 {
            get {
                return ResourceManager.GetString("TransmisionDatos12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Once telemetry has begun, the following available fields are:.
        /// </summary>
        public static string TransmisionDatos13 {
            get {
                return ResourceManager.GetString("TransmisionDatos13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fields with the transmitted information.
        /// </summary>
        public static string TransmisionDatos14 {
            get {
                return ResourceManager.GetString("TransmisionDatos14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Current data transmission information.
        /// </summary>
        public static string TransmisionDatos15 {
            get {
                return ResourceManager.GetString("TransmisionDatos15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Date and time that the next transmission will take place.
        /// </summary>
        public static string TransmisionDatos16 {
            get {
                return ResourceManager.GetString("TransmisionDatos16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a General well transmission information.
        /// </summary>
        public static string TransmisionDatos17 {
            get {
                return ResourceManager.GetString("TransmisionDatos17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Open window of selected well.
        /// </summary>
        public static string TransmisionDatos18 {
            get {
                return ResourceManager.GetString("TransmisionDatos18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Search field by: Name / Token / Type.
        /// </summary>
        public static string TransmisionDatos2 {
            get {
                return ResourceManager.GetString("TransmisionDatos2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Information table of the wells created.
        /// </summary>
        public static string TransmisionDatos3 {
            get {
                return ResourceManager.GetString("TransmisionDatos3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enter to modify the well.
        /// </summary>
        public static string TransmisionDatos4 {
            get {
                return ResourceManager.GetString("TransmisionDatos4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Open window to perform telemetry.
        /// </summary>
        public static string TransmisionDatos5 {
            get {
                return ResourceManager.GetString("TransmisionDatos5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Eliminate the existing well.
        /// </summary>
        public static string TransmisionDatos6 {
            get {
                return ResourceManager.GetString("TransmisionDatos6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a After exiting the {0}, a window will open which will consist of a series of empty and disabled fields to fill in.
        /// </summary>
        public static string TransmisionDatos7 {
            get {
                return ResourceManager.GetString("TransmisionDatos7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enable / Disable telemetry.
        /// </summary>
        public static string TransmisionDatos8 {
            get {
                return ResourceManager.GetString("TransmisionDatos8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enable / Disable streaming data.
        /// </summary>
        public static string TransmisionDatos9 {
            get {
                return ResourceManager.GetString("TransmisionDatos9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Version {0}.
        /// </summary>
        public static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You are running version {1}.
        /// </summary>
        public static string VersionNotes1 {
            get {
                return ResourceManager.GetString("VersionNotes1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a {0} has been updated to version {1}.
        /// </summary>
        public static string VersionNotes2 {
            get {
                return ResourceManager.GetString("VersionNotes2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Settings.
        /// </summary>
        public static string Visualizacion {
            get {
                return ResourceManager.GetString("Visualizacion", resourceCulture);
            }
        }
    }
}
