//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Languages {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Setups {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Setups() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Languages.Setups", typeof(Setups).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Check for Updates.
        /// </summary>
        public static string Actualizaciones {
            get {
                return ResourceManager.GetString("Actualizaciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Software update.
        /// </summary>
        public static string ActualizacionPrograma {
            get {
                return ResourceManager.GetString("ActualizacionPrograma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a © {0} EnTecPro I-Services..
        /// </summary>
        public static string Copyright {
            get {
                return ResourceManager.GetString("Copyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Number of decimal places.
        /// </summary>
        public static string Decimales {
            get {
                return ResourceManager.GetString("Decimales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Example:.
        /// </summary>
        public static string Ejemplo {
            get {
                return ResourceManager.GetString("Ejemplo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a English.
        /// </summary>
        public static string En {
            get {
                return ResourceManager.GetString("En", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Spanish.
        /// </summary>
        public static string Es {
            get {
                return ResourceManager.GetString("Es", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Spanish ( Mx ).
        /// </summary>
        public static string EsMx {
            get {
                return ResourceManager.GetString("EsMx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Guides.
        /// </summary>
        public static string Guia {
            get {
                return ResourceManager.GetString("Guia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Language.
        /// </summary>
        public static string Idioma {
            get {
                return ResourceManager.GetString("Idioma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a License Agreement.
        /// </summary>
        public static string LicenseAgreement {
            get {
                return ResourceManager.GetString("LicenseAgreement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Licenses.
        /// </summary>
        public static string Licenses {
            get {
                return ResourceManager.GetString("Licenses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a {0} is up to date.
        /// </summary>
        public static string MainLabel {
            get {
                return ResourceManager.GetString("MainLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Create new well
        ///- Use the keyboard shortcut Ctrl+N (Mac: Cmd+N);
        ///- From the menu, select {0}→{1}.....
        /// </summary>
        public static string newPozo1 {
            get {
                return ResourceManager.GetString("newPozo1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Name.
        /// </summary>
        public static string newPozo2 {
            get {
                return ResourceManager.GetString("newPozo2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Token *must be unique for each well.
        /// </summary>
        public static string newPozo3 {
            get {
                return ResourceManager.GetString("newPozo3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Type of well.
        /// </summary>
        public static string newPozo4 {
            get {
                return ResourceManager.GetString("newPozo4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a System of units to be used.
        /// </summary>
        public static string newPozo5 {
            get {
                return ResourceManager.GetString("newPozo5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a What&apos;s new:.
        /// </summary>
        public static string News {
            get {
                return ResourceManager.GetString("News", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Privacy.
        /// </summary>
        public static string Privacy {
            get {
                return ResourceManager.GetString("Privacy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Release Notes.
        /// </summary>
        public static string ReleaseNotes {
            get {
                return ResourceManager.GetString("ReleaseNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Terms.
        /// </summary>
        public static string Terms {
            get {
                return ResourceManager.GetString("Terms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Version {0}.
        /// </summary>
        public static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a {0} {1} is currently the newest version available.
        /// </summary>
        public static string VersionNotes1 {
            get {
                return ResourceManager.GetString("VersionNotes1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a {0} has been updated to version {1}.
        /// </summary>
        public static string VersionNotes2 {
            get {
                return ResourceManager.GetString("VersionNotes2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Settings.
        /// </summary>
        public static string Visualizacion {
            get {
                return ResourceManager.GetString("Visualizacion", resourceCulture);
            }
        }
    }
}
