//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Languages {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Siglas {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Siglas() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Languages.Siglas", typeof(Siglas).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a A.
        /// </summary>
        public static string Amperios {
            get {
                return ResourceManager.GetString("Amperios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a year.
        /// </summary>
        public static string Anio {
            get {
                return ResourceManager.GetString("Anio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a atm.
        /// </summary>
        public static string Atmosfera {
            get {
                return ResourceManager.GetString("Atmosfera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a bar.
        /// </summary>
        public static string Bar {
            get {
                return ResourceManager.GetString("Bar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a bo.
        /// </summary>
        public static string BarrilesAceite {
            get {
                return ResourceManager.GetString("BarrilesAceite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a bopy.
        /// </summary>
        public static string BarrilesAceitePorAnio {
            get {
                return ResourceManager.GetString("BarrilesAceitePorAnio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a bopd.
        /// </summary>
        public static string BarrilesAceitePorDia {
            get {
                return ResourceManager.GetString("BarrilesAceitePorDia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a boph.
        /// </summary>
        public static string BarrilesAceitePorHora {
            get {
                return ResourceManager.GetString("BarrilesAceitePorHora", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a bopm.
        /// </summary>
        public static string BarrilesAceitePorMinuto {
            get {
                return ResourceManager.GetString("BarrilesAceitePorMinuto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a bops.
        /// </summary>
        public static string BarrilesAceitePorSegundo {
            get {
                return ResourceManager.GetString("BarrilesAceitePorSegundo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a bbl.
        /// </summary>
        public static string BarrilesLiquido {
            get {
                return ResourceManager.GetString("BarrilesLiquido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a bpy.
        /// </summary>
        public static string BarrilesPetroleoPorAnio {
            get {
                return ResourceManager.GetString("BarrilesPetroleoPorAnio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a bpd.
        /// </summary>
        public static string BarrilesPetroleoPorDia {
            get {
                return ResourceManager.GetString("BarrilesPetroleoPorDia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a bph.
        /// </summary>
        public static string BarrilesPetroleoPorHora {
            get {
                return ResourceManager.GetString("BarrilesPetroleoPorHora", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a bpm.
        /// </summary>
        public static string BarrilesPetroleoPorMinuto {
            get {
                return ResourceManager.GetString("BarrilesPetroleoPorMinuto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a bps.
        /// </summary>
        public static string BarrilesPetroleoPorSegundo {
            get {
                return ResourceManager.GetString("BarrilesPetroleoPorSegundo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a BBL/STB.
        /// </summary>
        public static string BarrilPetroleoPorBarrilTanqueExistencias {
            get {
                return ResourceManager.GetString("BarrilPetroleoPorBarrilTanqueExistencias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a STB/SCF.
        /// </summary>
        public static string BarrilTanqueReservaPorPieCubicoEstandar {
            get {
                return ResourceManager.GetString("BarrilTanqueReservaPorPieCubicoEstandar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a hp.
        /// </summary>
        public static string Caballo {
            get {
                return ResourceManager.GetString("Caballo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a hp (UK).
        /// </summary>
        public static string CaballoUk {
            get {
                return ResourceManager.GetString("CaballoUk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a °C.
        /// </summary>
        public static string Celsius {
            get {
                return ResourceManager.GetString("Celsius", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a cm.
        /// </summary>
        public static string Centimetro {
            get {
                return ResourceManager.GetString("Centimetro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a cm².
        /// </summary>
        public static string CentimetroElevadoDos {
            get {
                return ResourceManager.GetString("CentimetroElevadoDos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a cm³/year.
        /// </summary>
        public static string CentimetroElevadoTresPorAnio {
            get {
                return ResourceManager.GetString("CentimetroElevadoTresPorAnio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a cm³/day.
        /// </summary>
        public static string CentimetroElevadoTresPorDia {
            get {
                return ResourceManager.GetString("CentimetroElevadoTresPorDia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a cm³/hour.
        /// </summary>
        public static string CentimetroElevadoTresPorHora {
            get {
                return ResourceManager.GetString("CentimetroElevadoTresPorHora", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a cm³/min.
        /// </summary>
        public static string CentimetroElevadoTresPorMinuto {
            get {
                return ResourceManager.GetString("CentimetroElevadoTresPorMinuto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a cm³/sec.
        /// </summary>
        public static string CentimetroElevadoTresPorSegundo {
            get {
                return ResourceManager.GetString("CentimetroElevadoTresPorSegundo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ciclo/sec.
        /// </summary>
        public static string Ciclo_Segundo {
            get {
                return ResourceManager.GetString("Ciclo_Segundo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a C/sec.
        /// </summary>
        public static string CulombiosPorSegundo {
            get {
                return ResourceManager.GetString("CulombiosPorSegundo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a day.
        /// </summary>
        public static string Dia {
            get {
                return ResourceManager.GetString("Dia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a dyn.
        /// </summary>
        public static string Dina {
            get {
                return ResourceManager.GetString("Dina", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SPM.
        /// </summary>
        public static string EmboladaPorMinuto {
            get {
                return ResourceManager.GetString("EmboladaPorMinuto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a °F.
        /// </summary>
        public static string Fahrenheit {
            get {
                return ResourceManager.GetString("Fahrenheit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a -.
        /// </summary>
        public static string Fraccion {
            get {
                return ResourceManager.GetString("Fraccion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a GHz.
        /// </summary>
        public static string Gigahercio {
            get {
                return ResourceManager.GetString("Gigahercio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a °.
        /// </summary>
        public static string Grado {
            get {
                return ResourceManager.GetString("Grado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a °API.
        /// </summary>
        public static string GradosApi {
            get {
                return ResourceManager.GetString("GradosApi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a g.
        /// </summary>
        public static string Gramo {
            get {
                return ResourceManager.GetString("Gramo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a gf.
        /// </summary>
        public static string GramoFuerza {
            get {
                return ResourceManager.GetString("GramoFuerza", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SG.
        /// </summary>
        public static string GravedadEspecifica {
            get {
                return ResourceManager.GetString("GravedadEspecifica", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Hz.
        /// </summary>
        public static string Hercio {
            get {
                return ResourceManager.GetString("Hercio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a hour.
        /// </summary>
        public static string Hora {
            get {
                return ResourceManager.GetString("Hora", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a J/hour.
        /// </summary>
        public static string Julio_Hora {
            get {
                return ResourceManager.GetString("Julio_Hora", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a °K.
        /// </summary>
        public static string Kelvin {
            get {
                return ResourceManager.GetString("Kelvin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a kA.
        /// </summary>
        public static string Kiloamperios {
            get {
                return ResourceManager.GetString("Kiloamperios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a kg.
        /// </summary>
        public static string Kilogramo {
            get {
                return ResourceManager.GetString("Kilogramo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a kg/cm³.
        /// </summary>
        public static string Kilogramo_CentimetroElevadoTres {
            get {
                return ResourceManager.GetString("Kilogramo_CentimetroElevadoTres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a kgf.
        /// </summary>
        public static string KilogramoFuerza {
            get {
                return ResourceManager.GetString("KilogramoFuerza", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a kgf/cm².
        /// </summary>
        public static string KilogramoFuerza_CentimetroElevadoDos {
            get {
                return ResourceManager.GetString("KilogramoFuerza_CentimetroElevadoDos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a kHz.
        /// </summary>
        public static string Kilohercio {
            get {
                return ResourceManager.GetString("Kilohercio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a kJ/hour.
        /// </summary>
        public static string Kilojulio_Hora {
            get {
                return ResourceManager.GetString("Kilojulio_Hora", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a klb.
        /// </summary>
        public static string Kilolibra {
            get {
                return ResourceManager.GetString("Kilolibra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a klbf.
        /// </summary>
        public static string KilolibraFuerza {
            get {
                return ResourceManager.GetString("KilolibraFuerza", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a km.
        /// </summary>
        public static string Kilometro {
            get {
                return ResourceManager.GetString("Kilometro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a kN.
        /// </summary>
        public static string Kilonewton {
            get {
                return ResourceManager.GetString("Kilonewton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a kPa.
        /// </summary>
        public static string Kilopascal {
            get {
                return ResourceManager.GetString("Kilopascal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a kW.
        /// </summary>
        public static string Kilovatio {
            get {
                return ResourceManager.GetString("Kilovatio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a kPsi.
        /// </summary>
        public static string Kpsi {
            get {
                return ResourceManager.GetString("Kpsi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a lb.
        /// </summary>
        public static string Libra {
            get {
                return ResourceManager.GetString("Libra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a lb/cfs.
        /// </summary>
        public static string Libra_PieElevadoTres {
            get {
                return ResourceManager.GetString("Libra_PieElevadoTres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a lb/in³.
        /// </summary>
        public static string Libra_PulgadaElevadoTres {
            get {
                return ResourceManager.GetString("Libra_PulgadaElevadoTres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a lbf.
        /// </summary>
        public static string LibraFuerza {
            get {
                return ResourceManager.GetString("LibraFuerza", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a lbf/in².
        /// </summary>
        public static string LibraFuerza_PulgadaElevadoDos {
            get {
                return ResourceManager.GetString("LibraFuerza_PulgadaElevadoDos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a MHz.
        /// </summary>
        public static string Megahercio {
            get {
                return ResourceManager.GetString("Megahercio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a MPa.
        /// </summary>
        public static string Megapascal {
            get {
                return ResourceManager.GetString("Megapascal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a month.
        /// </summary>
        public static string Mes {
            get {
                return ResourceManager.GetString("Mes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a m.
        /// </summary>
        public static string Metro {
            get {
                return ResourceManager.GetString("Metro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a m³/year.
        /// </summary>
        public static string MetroCubicoPorAnio {
            get {
                return ResourceManager.GetString("MetroCubicoPorAnio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a m³/day.
        /// </summary>
        public static string MetroCubicoPorDia {
            get {
                return ResourceManager.GetString("MetroCubicoPorDia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a m³/hour.
        /// </summary>
        public static string MetroCubicoPorHora {
            get {
                return ResourceManager.GetString("MetroCubicoPorHora", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a m³/m³.
        /// </summary>
        public static string MetroCubicoPorMetroCubico {
            get {
                return ResourceManager.GetString("MetroCubicoPorMetroCubico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a m³/min.
        /// </summary>
        public static string MetroCubicoPorMinuto {
            get {
                return ResourceManager.GetString("MetroCubicoPorMinuto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a m³/sec.
        /// </summary>
        public static string MetroCubicoPorSegundo {
            get {
                return ResourceManager.GetString("MetroCubicoPorSegundo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a m².
        /// </summary>
        public static string MetroElevadoDos {
            get {
                return ResourceManager.GetString("MetroElevadoDos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a m³/year.
        /// </summary>
        public static string MetroElevadoTresPorAnio {
            get {
                return ResourceManager.GetString("MetroElevadoTresPorAnio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a m³/day.
        /// </summary>
        public static string MetroElevadoTresPorDia {
            get {
                return ResourceManager.GetString("MetroElevadoTresPorDia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a m³/hour.
        /// </summary>
        public static string MetroElevadoTresPorHora {
            get {
                return ResourceManager.GetString("MetroElevadoTresPorHora", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a m³/min.
        /// </summary>
        public static string MetroElevadoTresPorMinuto {
            get {
                return ResourceManager.GetString("MetroElevadoTresPorMinuto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a m³/sec.
        /// </summary>
        public static string MetroElevadoTresPorSegundo {
            get {
                return ResourceManager.GetString("MetroElevadoTresPorSegundo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mm³/year.
        /// </summary>
        public static string MilesMetroElevadoTresPorAnio {
            get {
                return ResourceManager.GetString("MilesMetroElevadoTresPorAnio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mm³/day.
        /// </summary>
        public static string MilesMetroElevadoTresPorDia {
            get {
                return ResourceManager.GetString("MilesMetroElevadoTresPorDia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mm³/hour.
        /// </summary>
        public static string MilesMetroElevadoTresPorHora {
            get {
                return ResourceManager.GetString("MilesMetroElevadoTresPorHora", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mm³/min.
        /// </summary>
        public static string MilesMetroElevadoTresPorMinuto {
            get {
                return ResourceManager.GetString("MilesMetroElevadoTresPorMinuto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mm³/sec.
        /// </summary>
        public static string MilesMetroElevadoTresPorSegundo {
            get {
                return ResourceManager.GetString("MilesMetroElevadoTresPorSegundo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mcfs/year.
        /// </summary>
        public static string MilesPieElevadoTresPorAnio {
            get {
                return ResourceManager.GetString("MilesPieElevadoTresPorAnio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mcfd.
        /// </summary>
        public static string MilesPieElevadoTresPorDia {
            get {
                return ResourceManager.GetString("MilesPieElevadoTresPorDia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mcfs/hour.
        /// </summary>
        public static string MilesPieElevadoTresPorHora {
            get {
                return ResourceManager.GetString("MilesPieElevadoTresPorHora", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mcfs/min.
        /// </summary>
        public static string MilesPieElevadoTresPorMinuto {
            get {
                return ResourceManager.GetString("MilesPieElevadoTresPorMinuto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mcfs/sec.
        /// </summary>
        public static string MilesPieElevadoTresPorSegundo {
            get {
                return ResourceManager.GetString("MilesPieElevadoTresPorSegundo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a mA.
        /// </summary>
        public static string Miliamperios {
            get {
                return ResourceManager.GetString("Miliamperios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a mm.
        /// </summary>
        public static string Milimetro {
            get {
                return ResourceManager.GetString("Milimetro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a mi.
        /// </summary>
        public static string MillaUs {
            get {
                return ResourceManager.GetString("MillaUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a MMm³/year.
        /// </summary>
        public static string MillonesMetroElevadoTresPorAnio {
            get {
                return ResourceManager.GetString("MillonesMetroElevadoTresPorAnio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a MMm³/day.
        /// </summary>
        public static string MillonesMetroElevadoTresPorDia {
            get {
                return ResourceManager.GetString("MillonesMetroElevadoTresPorDia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a MMm³/hour.
        /// </summary>
        public static string MillonesMetroElevadoTresPorHora {
            get {
                return ResourceManager.GetString("MillonesMetroElevadoTresPorHora", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a MMm³/min.
        /// </summary>
        public static string MillonesMetroElevadoTresPorMinuto {
            get {
                return ResourceManager.GetString("MillonesMetroElevadoTresPorMinuto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a MMm³/sec.
        /// </summary>
        public static string MillonesMetroElevadoTresPorSegundo {
            get {
                return ResourceManager.GetString("MillonesMetroElevadoTresPorSegundo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a MMcfs/year.
        /// </summary>
        public static string MillonesPieElevadoTresPorAnio {
            get {
                return ResourceManager.GetString("MillonesPieElevadoTresPorAnio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a MMcfd.
        /// </summary>
        public static string MillonesPieElevadoTresPorDia {
            get {
                return ResourceManager.GetString("MillonesPieElevadoTresPorDia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a MMcfs/hour.
        /// </summary>
        public static string MillonesPieElevadoTresPorHora {
            get {
                return ResourceManager.GetString("MillonesPieElevadoTresPorHora", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a MMcfs/min.
        /// </summary>
        public static string MillonesPieElevadoTresPorMinuto {
            get {
                return ResourceManager.GetString("MillonesPieElevadoTresPorMinuto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a MMcfs/sec.
        /// </summary>
        public static string MillonesPieElevadoTresPorSegundo {
            get {
                return ResourceManager.GetString("MillonesPieElevadoTresPorSegundo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a min.
        /// </summary>
        public static string Minuto {
            get {
                return ResourceManager.GetString("Minuto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a N.
        /// </summary>
        public static string Newton {
            get {
                return ResourceManager.GetString("Newton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a N/m².
        /// </summary>
        public static string Newton_MetroElevadoDos {
            get {
                return ResourceManager.GetString("Newton_MetroElevadoDos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a oz.
        /// </summary>
        public static string Onza {
            get {
                return ResourceManager.GetString("Onza", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ozf.
        /// </summary>
        public static string OnzaFuerza {
            get {
                return ResourceManager.GetString("OnzaFuerza", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pa.
        /// </summary>
        public static string Pascal {
            get {
                return ResourceManager.GetString("Pascal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ft.
        /// </summary>
        public static string Pie {
            get {
                return ResourceManager.GetString("Pie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SCF/STB.
        /// </summary>
        public static string PieCubicoEstandarPorBarrilTanqueReserva {
            get {
                return ResourceManager.GetString("PieCubicoEstandarPorBarrilTanqueReserva", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ft².
        /// </summary>
        public static string PieElevadoDos {
            get {
                return ResourceManager.GetString("PieElevadoDos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a cfs/year.
        /// </summary>
        public static string PieElevadoTresPorAnio {
            get {
                return ResourceManager.GetString("PieElevadoTresPorAnio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a cfd.
        /// </summary>
        public static string PieElevadoTresPorDia {
            get {
                return ResourceManager.GetString("PieElevadoTresPorDia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a cfs/hour.
        /// </summary>
        public static string PieElevadoTresPorHora {
            get {
                return ResourceManager.GetString("PieElevadoTresPorHora", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a cfs/min.
        /// </summary>
        public static string PieElevadoTresPorMinuto {
            get {
                return ResourceManager.GetString("PieElevadoTresPorMinuto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a cfs/sec.
        /// </summary>
        public static string PieElevadoTresPorSegundo {
            get {
                return ResourceManager.GetString("PieElevadoTresPorSegundo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a cfs/year.
        /// </summary>
        public static string PiesCubicosPorAnio {
            get {
                return ResourceManager.GetString("PiesCubicosPorAnio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a cfd.
        /// </summary>
        public static string PiesCubicosPorDia {
            get {
                return ResourceManager.GetString("PiesCubicosPorDia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a cfs/hour.
        /// </summary>
        public static string PiesCubicosPorHora {
            get {
                return ResourceManager.GetString("PiesCubicosPorHora", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a cfs/min.
        /// </summary>
        public static string PiesCubicosPorMinuto {
            get {
                return ResourceManager.GetString("PiesCubicosPorMinuto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a cfs/sec.
        /// </summary>
        public static string PiesCubicosPorSegundo {
            get {
                return ResourceManager.GetString("PiesCubicosPorSegundo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a %.
        /// </summary>
        public static string Porcentaje {
            get {
                return ResourceManager.GetString("Porcentaje", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a pdl.
        /// </summary>
        public static string Poundal {
            get {
                return ResourceManager.GetString("Poundal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Psi.
        /// </summary>
        public static string Psi {
            get {
                return ResourceManager.GetString("Psi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a in.
        /// </summary>
        public static string Pulgada {
            get {
                return ResourceManager.GetString("Pulgada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a inH₂O.
        /// </summary>
        public static string PulgadaAgua60GradosF {
            get {
                return ResourceManager.GetString("PulgadaAgua60GradosF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a in².
        /// </summary>
        public static string PulgadaElevadoDos {
            get {
                return ResourceManager.GetString("PulgadaElevadoDos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a in³/year.
        /// </summary>
        public static string PulgadaElevadoTresPorAnio {
            get {
                return ResourceManager.GetString("PulgadaElevadoTresPorAnio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a in³/day.
        /// </summary>
        public static string PulgadaElevadoTresPorDia {
            get {
                return ResourceManager.GetString("PulgadaElevadoTresPorDia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a in³/hour.
        /// </summary>
        public static string PulgadaElevadoTresPorHora {
            get {
                return ResourceManager.GetString("PulgadaElevadoTresPorHora", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a in³/min.
        /// </summary>
        public static string PulgadaElevadoTresPorMinuto {
            get {
                return ResourceManager.GetString("PulgadaElevadoTresPorMinuto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a in³/sec.
        /// </summary>
        public static string PulgadaElevadoTresPorSegundo {
            get {
                return ResourceManager.GetString("PulgadaElevadoTresPorSegundo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a rad.
        /// </summary>
        public static string Radian {
            get {
                return ResourceManager.GetString("Radian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a °R.
        /// </summary>
        public static string Rankine {
            get {
                return ResourceManager.GetString("Rankine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a rev.
        /// </summary>
        public static string Revolucion {
            get {
                return ResourceManager.GetString("Revolucion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a rev/day.
        /// </summary>
        public static string Revolucion_Dia {
            get {
                return ResourceManager.GetString("Revolucion_Dia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a rev/hour.
        /// </summary>
        public static string Revolucion_Hora {
            get {
                return ResourceManager.GetString("Revolucion_Hora", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a RPM.
        /// </summary>
        public static string Revolucion_Minuto {
            get {
                return ResourceManager.GetString("Revolucion_Minuto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a rev/sec.
        /// </summary>
        public static string Revolucion_Segundo {
            get {
                return ResourceManager.GetString("Revolucion_Segundo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a sec.
        /// </summary>
        public static string Segundo {
            get {
                return ResourceManager.GetString("Segundo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a tn, st.
        /// </summary>
        public static string Ton {
            get {
                return ResourceManager.GetString("Ton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Torr.
        /// </summary>
        public static string Torr {
            get {
                return ResourceManager.GetString("Torr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a W.
        /// </summary>
        public static string Vatio {
            get {
                return ResourceManager.GetString("Vatio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a yd.
        /// </summary>
        public static string Yarda {
            get {
                return ResourceManager.GetString("Yarda", resourceCulture);
            }
        }
    }
}
