//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Languages {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SystemWell {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SystemWell() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Languages.SystemWell", typeof(SystemWell).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PCP.
        /// </summary>
        public static string BCP {
            get {
                return ResourceManager.GetString("BCP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ESP.
        /// </summary>
        public static string BEC {
            get {
                return ResourceManager.GetString("BEC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a JP.
        /// </summary>
        public static string BJP {
            get {
                return ResourceManager.GetString("BJP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a RP.
        /// </summary>
        public static string BM {
            get {
                return ResourceManager.GetString("BM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CGL.
        /// </summary>
        public static string BN {
            get {
                return ResourceManager.GetString("BN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a GL.
        /// </summary>
        public static string BNI {
            get {
                return ResourceManager.GetString("BNI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Electro centrifugal.
        /// </summary>
        public static string ElectroCentrifugal {
            get {
                return ResourceManager.GetString("ElectroCentrifugal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a NF.
        /// </summary>
        public static string FL {
            get {
                return ResourceManager.GetString("FL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Gas.
        /// </summary>
        public static string FLG {
            get {
                return ResourceManager.GetString("FLG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Flowing.
        /// </summary>
        public static string Flowing {
            get {
                return ResourceManager.GetString("Flowing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Gas flowing.
        /// </summary>
        public static string GasFlowing {
            get {
                return ResourceManager.GetString("GasFlowing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Intermittent pneumatic.
        /// </summary>
        public static string IntermittentPneumatic {
            get {
                return ResourceManager.GetString("IntermittentPneumatic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Jet.
        /// </summary>
        public static string Jet {
            get {
                return ResourceManager.GetString("Jet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mechanical.
        /// </summary>
        public static string Mechanical {
            get {
                return ResourceManager.GetString("Mechanical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pneumatic.
        /// </summary>
        public static string Pneumatic {
            get {
                return ResourceManager.GetString("Pneumatic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Progressive cavity.
        /// </summary>
        public static string ProgressiveCavity {
            get {
                return ResourceManager.GetString("ProgressiveCavity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a {0} pumping.
        /// </summary>
        public static string Pump {
            get {
                return ResourceManager.GetString("Pump", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a {0} pumping well.
        /// </summary>
        public static string WellPump {
            get {
                return ResourceManager.GetString("WellPump", resourceCulture);
            }
        }
    }
}
